version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: "/cicd/dockerhub:username"
    DOCKERHUB_ACCESS_TOKEN: "/cicd/dockerhub:token"
  variables:
    AWS_REGION: "ap-south-1"
    ECR_IDEAHUB_REPO: "925413096657.dkr.ecr.ap-south-1.amazonaws.com/ideahub-image"
    
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_IDEAHUB_REPO
      - echo "Logging in to Docker Hub"
      - echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin 
      - echo Retrieving secrets from AWS Secrets Manager...
      - export DJANGO_SUPERUSER_USERNAME=$(aws secretsmanager get-secret-value --secret-id my-django-app-superuser --query 'SecretString' --output text | jq -r '.DJANGO_SUPERUSER_USERNAME')
      - export DJANGO_SUPERUSER_EMAIL=$(aws secretsmanager get-secret-value --secret-id my-django-app-superuser --query 'SecretString' --output text | jq -r '.DJANGO_SUPERUSER_EMAIL')
      - export DJANGO_SUPERUSER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id my-django-app-superuser --query 'SecretString' --output text | jq -r '.DJANGO_SUPERUSER_PASSWORD')
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg DJANGO_SUPERUSER_USERNAME --build-arg DJANGO_SUPERUSER_EMAIL --build-arg DJANGO_SUPERUSER_PASSWORD -t ideahub-image .

  post_build:
    commands:
      - echo Tagging in progress...
      - docker tag ideahub-image:latest $ECR_IDEAHUB_REPO:latest
      - echo Pushing the Docker image...
      - docker push $ECR_IDEAHUB_REPO:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ideahub-django-container","imageUri":"%s"}]' $ECR_IDEAHUB_REPO:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
